### ISSUE TITLE
Link to Example CDC Measure is broken

### ISSUE THREAD

**Issue by michaeldonnelly** [HL7/fhir-saner#6]
On the main page of the IG on CIB http://build.fhir.org/ig/HL7/fhir-saner/ there's a link to ​Measure: CDC Patient Impact and Hospital Capacity, but clicking on it gets a 404 error. 

http://build.fhir.org/ig/HL7/fhir-saner/Measure-CDCPatientImpactandHospitalCapacity.json.html

**Comment by keithboone** [comment]
This has been corrected.
